title: 安卓教程
description: Android tutorials for beginners
baseurl: "/android-tutorials"
url: "https://jame-louis.github.io"

# Collections
collections:
  tutorials:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"

# Sass
sass:
  sass_dir: _sass
  style: compressed

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
    span:
      line_numbers: false
  auto_ids: true
  footnote_nr: 1

picture:
  source: "assets/images"
  output: "generated"
  markup: "picture"

# For GitHub Pages users
gems:
  - rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll_picture_tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  
  # _config.yml
giscus:
  enabled: true
  repo: "jame-louis/android-tutorials"
  repo_id: "R_kgDOQd_G4g"
  category: "Announcements"
  category_id: "DIC_kwDOQd_G4s4CzLNF"
  mapping: "url"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "light"
  lang: "zh-CN"
  loading: "lazy"